apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}

type: Opaque
stringData:
  SECRET_KEY: "{{ .Values.backend.env.SECRET_KEY }}"
