apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env
  namespace: {{ .Values.namespace }}
  
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}

data:
  DJANGO_DEBUG: "{{ .Values.backend.env.DJANGO_DEBUG }}"
  DJANGO_ALLOWED_HOSTS: "{{ .Values.backend.env.DJANGO_ALLOWED_HOSTS }}"
  DATABASE_URL: "{{ .Values.backend.env.DATABASE_URL }}"
