apiVersion: batch/v1
kind: CronJob
metadata:
  name: backend-clearsessions
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: clearsessions
              image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
              imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
              envFrom:
                - configMapRef:
                    name: backend-env
                - secretRef:
                    name: backend-secret
              command: ["python","manage.py","clearsessions"]
