{{- if .Values.celery.flower.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
  namespace: {{ .Values.namespace }}
  labels:
    app: flower
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
        - name: flower
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: backend-env
            - secretRef:
                name: backend-secret
          command: ["celery"]
          args: ["-A", "rmq.celery_app", "flower", "--port={{ .Values.celery.flower.port }}"]
---
apiVersion: v1
kind: Service
metadata:
  name: flower-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: flower
  ports:
    - port: {{ .Values.celery.flower.port }}
      targetPort: {{ .Values.celery.flower.port }}
      nodePort: 30555
{{- end }}
